language: android
android:
  components:
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
